### ISSUE TITLE
Nova setup fails on mcp decompilation

### ISSUE THREAD

**Issue by Haruki1** [NovaMods/nova-renderer#113]
When running .\gradlew setup from windows 10 powershell it fails on mcp decompiling and gives me this.

```
PS C:\users\haruki\Desktop\nova-renderer> .\gradlew setup
Configuring for MSVC 64-bit
:verifyEnvironment
CMake found!
Could not find GCC. If you want to use GCC to compile Nova, please install it to your PATH and try again
:downloadMcp
Download http://www.modcoderpack.com/files/mcp931.zip
:decompileMcp
== MCP 9.30 (data: 9.31, client: 1.10, server: 1.10) ==
"scalac" is not found on the PATH.  Scala files will not be recompiled
FATAL ERROR
Traceback (most recent call last):
  File "C:\Users\Haruki\Desktop\nova-renderer/mcp/runtime/decompile.py", line 59, in decompile
    commands = Commands(conffile, verify=True, no_patch=no_patch, workdir=workdir, json=json)
  File "C:\Users\Haruki\Desktop\nova-renderer\mcp\runtime\commands.py", line 210, in __init__
    self.readcommands(verify, no_patch=no_patch)
  File "C:\Users\Haruki\Desktop\nova-renderer\mcp\runtime\commands.py", line 318, in readcommands
    error=False)
  File "C:\Users\Haruki\Desktop\nova-renderer\mcp\runtime\commands.py", line 234, in checkcommand
    output = output.splitlines()[0]
IndexError: list index out of range
:decompileMcp FAILED

FAILURE: Build failed with an exception.

* Where:
Script 'C:\Users\Haruki\Desktop\nova-renderer\setup.gradle' line: 84

* What went wrong:
Execution failed for task ':decompileMcp'.
> Process 'command 'C:\Users\Haruki\Desktop\nova-renderer/mcp/runtime/bin/python/python_mcp'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 17.815 secs
PS C:\users\haruki\Desktop\nova-renderer>
```

**Comment by DethRaid** [comment]
I do love debugging MCP...

**Comment by DethRaid** [comment]
I saw that you had run Nova. How did you solve this issue?

**Comment by Haruki1** [comment]
Patch file must have line endings in unix style. if they are in windows style it fails to apply.

**Comment by DethRaid** [comment]
Closing this issue since you got it working
