### ISSUE TITLE
java.lang.reflect.InvocationTargetException: null

### ISSUE THREAD

**Issue by darkhpp** [NovaMods/nova-renderer#162]
```
> java.lang.reflect.InvocationTargetException: null
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_45]
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
> 	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_45]
> 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
> 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
> Caused by: java.lang.NullPointerException
> 	at Config.getAnisotropicFilterLevel(Config.java:1646) ~[Config.class:?]
> 	at Config.isMultiTexture(Config.java:1687) ~[Config.class:?]
> 	at net.minecraft.client.renderer.texture.TextureAtlasSprite.<init>(TextureAtlasSprite.java:84) ~[cdq.class:?]
> 	at net.minecraft.client.renderer.texture.TextureMap.<init>(TextureMap.java:104) ~[cdp.class:?]
> 	at net.minecraft.client.renderer.texture.TextureMap.<init>(TextureMap.java:95) ~[cdp.class:?]
> 	at net.minecraft.client.renderer.texture.TextureMap.<init>(TextureMap.java:83) ~[cdp.class:?]
> 	at com.continuum.nova.NovaRenderer.<init>(NovaRenderer.java:60) ~[NovaRenderer.class:?]
> 	at com.continuum.nova.NovaRenderer.create(NovaRenderer.java:105) ~[NovaRenderer.class:?]
> 	at net.minecraft.client.Minecraft.handler$constructorEnd$zzg000(Minecraft.java:3543) ~[bib.class:?]
> 	at net.minecraft.client.Minecraft.<init>(Minecraft.java:369) ~[bib.class:?]
> 	at net.minecraft.client.main.Main.main(SourceFile:123) ~[Main.class:?]
> 	... 6 more
> Exception in thread "Client thread" [07:17:08] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
> [07:17:08] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
> [07:17:08] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.SecurityManager.checkExit(Unknown Source)
> [07:17:08] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.Runtime.exit(Unknown Source)
> [07:17:08] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.System.exit(Unknown Source)
> [07:17:08] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
> [07:17:08] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by DethRaid** [comment]
How did you get this error? What were you doing? How did you get Nova (download a GitHub release, compile from source (what branch?), something else)?

**Comment by SevastyanDark** [comment]
@DethRaid I have downloaded this from latest release on github. This occurs when starting minecraft, not even logo;

**Comment by DethRaid** [comment]
The releases on GitHub are known to be super unstable. We're rewriting Nova to increase stability but it's a large task
