### ISSUE TITLE
Caused by: java.lang.NullPointerException

### ISSUE THREAD

**Issue by alexandrage** [NovaMods/nova-renderer#164]
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Minecraft Forge (forge)
Caused by: java.lang.NullPointerException
	at net.minecraftforge.fml.client.FMLClientHandler.reloadCreativeSettings(FMLClientHandler.java:1093)
	at net.minecraftforge.fml.common.FMLCommonHandler.reloadCreativeSettings(FMLCommonHandler.java:783)
	at net.minecraftforge.common.ForgeModContainer.mappingChanged(ForgeModContainer.java:575)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
	at net.minecraftforge.fml.common.Loader.fireRemapEvent(Loader.java:924)
	at net.minecraftforge.registries.GameData.freezeData(GameData.java:237)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:753)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:3650)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_172, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 244417784 bytes (233 MB) / 564625408 bytes (538 MB) up to 8576565248 bytes (8179 MB)
	JVM Flags: 6 total; -Xmx8G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.4.2759 5 mods loaded, 5 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State   | ID                 | Version      | Source                        | Signature                                |
	|:------- |:------------------ |:------------ |:----------------------------- |:---------------------------------------- |
	| UCHIJA  | minecraft          | 1.12.2       | minecraft.jar                 | None                                     |
	| UCHIJA  | mcp                | 9.42         | minecraft.jar                 | None                                     |
	| UCHIJA  | FML                | 8.0.99.99    | forge-1.12.2-14.23.4.2759.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAE | forge              | 14.23.4.2759 | forge-1.12.2-14.23.4.2759.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJA  | nova-renderer-core | 0.0.1        | minecraft.jar                 | None                                     |

	Loaded coremods (and transformers): 
NovaForgeCoreMod (nova-renderer-0.7.3-SNAPSHOT-all.jar)
  com.continuum.nova.transformer.NovaClassTransformer

**Comment by Janrupf** [comment]
The old versions are not maintained anymore in favor of the rwrite so we wont provide support here. However, going to mark this as a bug anyway
