### ISSUE TITLE
Can't start minecraft. Sound system issue.

### ISSUE THREAD

**Issue by XakepSDK** [NovaMods/nova-renderer#38]
```
user@user-pc:~/Desktop/nova/nova-renderer$ ./nova.sh start
[15:37:36] [Client thread/INFO]: Setting user: Player570
[15:37:36] [Client thread/INFO]: PID: 20843@user-pc
2017-06-17 15:37:36,683 INFO  [default] Loading config from config/config.json
03:37:36 [INFO ] glfw_gl_window.cpp 43 - GLFW window created
03:37:36 [INFO ] glfw_gl_window.cpp 46 - Hooked into RenderDoc
03:37:36 [INFO ] glfw_gl_window.cpp 57 - Vendor: Intel Open Source Technology Center
03:37:36 [TRACE] gl_uniform_buffer.h 23 - creating ubo gui_uniforms with size: 148
03:37:36 [INFO ] uniform_buffer_store.cpp 16 - Initialized uniform buffer store
03:37:36 [INFO ] texture_manager.cpp 12 - Creating the Texture Manager
03:37:36 [INFO ] texture_manager.cpp 14 - Texture manager created
03:37:36 [DEBUG] uniform_buffer_store.cpp 28 - UBO store received updated config
03:37:36 [TRACE] uniform_buffer_store.cpp 70 - gui_uniform_variables buffer: gbufferModelView: 
{ 0.00468384 0 0 0
 -0 -0.00833333 -0 -0
 0 0 1 1
 -1 1 0 0 } gbufferProjection: 
{ 1 0 0 0
 0 1 0 0
 0 0 1 1
 0 0 0 0 } aspectRatio: 1.77917 viewWidth: 854 viewHeight: 480 frameTimeCounter: 0 hideGUI: 0
03:37:36 [TRACE] gl_uniform_buffer.h 43 - sending date with size: 148 to ubo gui_uniforms
03:37:36 [DEBUG] uniform_buffer_store.cpp 73 - Updated GUI UBO
03:37:36 [INFO ] glfw_gl_window.cpp 152 - gl_glfw_window received the updated config
03:37:36 [INFO ] nova_renderer.cpp 236 - Loading shaderpack default
03:37:36 [TRACE] shader_loading.cpp 45 - Loading shaderpack default from a regular folder
03:37:36 [TRACE] shader_loading.cpp 175 - Loading shader file shaderpacks/default/shaders/composite.vsh
03:37:36 [WARN ] shader_loading.cpp 181 - Could not read file shaderpacks/default/shaders/composite.vsh
03:37:36 [TRACE] shader_loading.cpp 175 - Loading shader file shaderpacks/default/shaders/composite.vert
03:37:36 [WARN ] shader_loading.cpp 181 - Could not read file shaderpacks/default/shaders/composite.vert
03:37:36 [TRACE] shader_loading.cpp 175 - Loading shader file shaderpacks/default/shaders/composite.vert.spv
03:37:36 [WARN ] shader_loading.cpp 181 - Could not read file shaderpacks/default/shaders/composite.vert.spv
03:37:36 [ERROR] shader_loading.cpp 100 - std::exception
03:37:36 [TRACE] shader_loading.cpp 175 - Loading shader file shaderpacks/default/shaders/gbuffers_basic.vsh
03:37:36 [WARN ] shader_loading.cpp 181 - Could not read file shaderpacks/default/shaders/gbuffers_basic.vsh
03:37:36 [TRACE] shader_loading.cpp 175 - Loading shader file shaderpacks/default/shaders/gbuffers_basic.vert
03:37:36 [WARN ] shader_loading.cpp 181 - Could not read file shaderpacks/default/shaders/gbuffers_basic.vert
03:37:36 [TRACE] shader_loading.cpp 175 - Loading shader file shaderpacks/default/shaders/gbuffers_basic.vert.spv
03:37:36 [WARN ] shader_loading.cpp 181 - Could not read file shaderpacks/default/shaders/gbuffers_basic.vert.spv
03:37:36 [ERROR] shader_loading.cpp 100 - std::exception
03:37:36 [TRACE] shader_loading.cpp 175 - Loading shader file shaderpacks/default/shaders/gbuffers_skybasic.vsh
03:37:36 [WARN ] shader_loading.cpp 181 - Could not read file shaderpacks/default/shaders/gbuffers_skybasic.vsh
03:37:36 [TRACE] shader_loading.cpp 175 - Loading shader file shaderpacks/default/shaders/gbuffers_skybasic.vert
03:37:36 [WARN ] shader_loading.cpp 181 - Could not read file shaderpacks/default/shaders/gbuffers_skybasic.vert
03:37:36 [TRACE] shader_loading.cpp 175 - Loading shader file shaderpacks/default/shaders/gbuffers_skybasic.vert.spv
03:37:36 [WARN ] shader_loading.cpp 181 - Could not read file shaderpacks/default/shaders/gbuffers_skybasic.vert.spv
03:37:36 [ERROR] shader_loading.cpp 100 - std::exception
03:37:36 [TRACE] shader_loading.cpp 175 - Loading shader file shaderpacks/default/shaders/gbuffers_textured.vsh
03:37:36 [WARN ] shader_loading.cpp 181 - Could not read file shaderpacks/default/shaders/gbuffers_textured.vsh
03:37:36 [TRACE] shader_loading.cpp 175 - Loading shader file shaderpacks/default/shaders/gbuffers_textured.vert
03:37:36 [WARN ] shader_loading.cpp 181 - Could not read file shaderpacks/default/shaders/gbuffers_textured.vert
03:37:36 [TRACE] shader_loading.cpp 175 - Loading shader file shaderpacks/default/shaders/gbuffers_textured.vert.spv
03:37:36 [WARN ] shader_loading.cpp 181 - Could not read file shaderpacks/default/shaders/gbuffers_textured.vert.spv
03:37:36 [ERROR] shader_loading.cpp 100 - std::exception
03:37:36 [TRACE] shader_loading.cpp 175 - Loading shader file shaderpacks/default/shaders/gbuffers_spidereyes.vsh
03:37:36 [WARN ] shader_loading.cpp 181 - Could not read file shaderpacks/default/shaders/gbuffers_spidereyes.vsh
03:37:36 [TRACE] shader_loading.cpp 175 - Loading shader file shaderpacks/default/shaders/gbuffers_spidereyes.vert
03:37:36 [WARN ] shader_loading.cpp 181 - Could not read file shaderpacks/default/shaders/gbuffers_spidereyes.vert
03:37:36 [TRACE] shader_loading.cpp 175 - Loading shader file shaderpacks/default/shaders/gbuffers_spidereyes.vert.spv
03:37:36 [WARN ] shader_loading.cpp 181 - Could not read file shaderpacks/default/shaders/gbuffers_spidereyes.vert.spv
03:37:36 [ERROR] shader_loading.cpp 100 - std::exception
03:37:36 [TRACE] shader_loading.cpp 175 - Loading shader file shaderpacks/default/shaders/gbuffers_armor_glint.vsh
03:37:36 [WARN ] shader_loading.cpp 181 - Could not read file shaderpacks/default/shaders/gbuffers_armor_glint.vsh
03:37:36 [TRACE] shader_loading.cpp 175 - Loading shader file shaderpacks/default/shaders/gbuffers_armor_glint.vert
03:37:36 [WARN ] shader_loading.cpp 181 - Could not read file shaderpacks/default/shaders/gbuffers_armor_glint.vert
03:37:36 [TRACE] shader_loading.cpp 175 - Loading shader file shaderpacks/default/shaders/gbuffers_armor_glint.vert.spv
03:37:36 [WARN ] shader_loading.cpp 181 - Could not read file shaderpacks/default/shaders/gbuffers_armor_glint.vert.spv
03:37:36 [ERROR] shader_loading.cpp 100 - std::exception
03:37:36 [TRACE] shader_loading.cpp 175 - Loading shader file shaderpacks/default/shaders/gbuffers_clouds.vsh
03:37:36 [WARN ] shader_loading.cpp 181 - Could not read file shaderpacks/default/shaders/gbuffers_clouds.vsh
03:37:36 [TRACE] shader_loading.cpp 175 - Loading shader file shaderpacks/default/shaders/gbuffers_clouds.vert
03:37:36 [WARN ] shader_loading.cpp 181 - Could not read file shaderpacks/default/shaders/gbuffers_clouds.vert
03:37:36 [TRACE] shader_loading.cpp 175 - Loading shader file shaderpacks/default/shaders/gbuffers_clouds.vert.spv
03:37:36 [WARN ] shader_loading.cpp 181 - Could not read file shaderpacks/default/shaders/gbuffers_clouds.vert.spv
03:37:36 [ERROR] shader_loading.cpp 100 - std::exception
03:37:36 [TRACE] shader_loading.cpp 175 - Loading shader file shaderpacks/default/shaders/gbuffers_skytextured.vsh
03:37:36 [WARN ] shader_loading.cpp 181 - Could not read file shaderpacks/default/shaders/gbuffers_skytextured.vsh
03:37:36 [TRACE] shader_loading.cpp 175 - Loading shader file shaderpacks/default/shaders/gbuffers_skytextured.vert
03:37:36 [WARN ] shader_loading.cpp 181 - Could not read file shaderpacks/default/shaders/gbuffers_skytextured.vert
03:37:36 [TRACE] shader_loading.cpp 175 - Loading shader file shaderpacks/default/shaders/gbuffers_skytextured.vert.spv
03:37:36 [WARN ] shader_loading.cpp 181 - Could not read file shaderpacks/default/shaders/gbuffers_skytextured.vert.spv
03:37:36 [ERROR] shader_loading.cpp 100 - std::exception
03:37:36 [TRACE] shader_loading.cpp 175 - Loading shader file shaderpacks/default/shaders/gbuffers_textures_lit.vsh
03:37:36 [WARN ] shader_loading.cpp 181 - Could not read file shaderpacks/default/shaders/gbuffers_textures_lit.vsh
03:37:36 [TRACE] shader_loading.cpp 175 - Loading shader file shaderpacks/default/shaders/gbuffers_textures_lit.vert
03:37:36 [WARN ] shader_loading.cpp 181 - Could not read file shaderpacks/default/shaders/gbuffers_textures_lit.vert
03:37:36 [TRACE] shader_loading.cpp 175 - Loading shader file shaderpacks/default/shaders/gbuffers_textures_lit.vert.spv
03:37:36 [WARN ] shader_loading.cpp 181 - Could not read file shaderpacks/default/shaders/gbuffers_textures_lit.vert.spv
03:37:36 [ERROR] shader_loading.cpp 100 - std::exception
03:37:36 [TRACE] shader_loading.cpp 175 - Loading shader file shaderpacks/default/shaders/gbuffers_entities.vsh
03:37:36 [WARN ] shader_loading.cpp 181 - Could not read file shaderpacks/default/shaders/gbuffers_entities.vsh
03:37:36 [TRACE] shader_loading.cpp 175 - Loading shader file shaderpacks/default/shaders/gbuffers_entities.vert
03:37:36 [WARN ] shader_loading.cpp 181 - Could not read file shaderpacks/default/shaders/gbuffers_entities.vert
03:37:36 [TRACE] shader_loading.cpp 175 - Loading shader file shaderpacks/default/shaders/gbuffers_entities.vert.spv
03:37:36 [WARN ] shader_loading.cpp 181 - Could not read file shaderpacks/default/shaders/gbuffers_entities.vert.spv
03:37:36 [ERROR] shader_loading.cpp 100 - std::exception
03:37:36 [TRACE] shader_loading.cpp 175 - Loading shader file shaderpacks/default/shaders/gbuffers_hand.vsh
03:37:36 [WARN ] shader_loading.cpp 181 - Could not read file shaderpacks/default/shaders/gbuffers_hand.vsh
03:37:36 [TRACE] shader_loading.cpp 175 - Loading shader file shaderpacks/default/shaders/gbuffers_hand.vert
03:37:36 [WARN ] shader_loading.cpp 181 - Could not read file shaderpacks/default/shaders/gbuffers_hand.vert
03:37:36 [TRACE] shader_loading.cpp 175 - Loading shader file shaderpacks/default/shaders/gbuffers_hand.vert.spv
03:37:36 [WARN ] shader_loading.cpp 181 - Could not read file shaderpacks/default/shaders/gbuffers_hand.vert.spv
03:37:36 [ERROR] shader_loading.cpp 100 - std::exception
03:37:36 [TRACE] shader_loading.cpp 175 - Loading shader file shaderpacks/default/shaders/gbuffers_weather.vsh
03:37:36 [WARN ] shader_loading.cpp 181 - Could not read file shaderpacks/default/shaders/gbuffers_weather.vsh
03:37:36 [TRACE] shader_loading.cpp 175 - Loading shader file shaderpacks/default/shaders/gbuffers_weather.vert
03:37:36 [WARN ] shader_loading.cpp 181 - Could not read file shaderpacks/default/shaders/gbuffers_weather.vert
03:37:36 [TRACE] shader_loading.cpp 175 - Loading shader file shaderpacks/default/shaders/gbuffers_weather.vert.spv
03:37:36 [WARN ] shader_loading.cpp 181 - Could not read file shaderpacks/default/shaders/gbuffers_weather.vert.spv
03:37:36 [ERROR] shader_loading.cpp 100 - std::exception
03:37:36 [TRACE] shader_loading.cpp 175 - Loading shader file shaderpacks/default/shaders/gbuffers_terrain.vsh
03:37:36 [WARN ] shader_loading.cpp 181 - Could not read file shaderpacks/default/shaders/gbuffers_terrain.vsh
03:37:36 [TRACE] shader_loading.cpp 175 - Loading shader file shaderpacks/default/shaders/gbuffers_terrain.vert
03:37:36 [WARN ] shader_loading.cpp 181 - Could not read file shaderpacks/default/shaders/gbuffers_terrain.vert
03:37:36 [TRACE] shader_loading.cpp 175 - Loading shader file shaderpacks/default/shaders/gbuffers_terrain.vert.spv
03:37:36 [WARN ] shader_loading.cpp 181 - Could not read file shaderpacks/default/shaders/gbuffers_terrain.vert.spv
03:37:36 [ERROR] shader_loading.cpp 100 - std::exception
03:37:36 [TRACE] shader_loading.cpp 175 - Loading shader file shaderpacks/default/shaders/gbuffers_damagedblock.vsh
03:37:36 [WARN ] shader_loading.cpp 181 - Could not read file shaderpacks/default/shaders/gbuffers_damagedblock.vsh
03:37:36 [TRACE] shader_loading.cpp 175 - Loading shader file shaderpacks/default/shaders/gbuffers_damagedblock.vert
03:37:36 [WARN ] shader_loading.cpp 181 - Could not read file shaderpacks/default/shaders/gbuffers_damagedblock.vert
03:37:36 [TRACE] shader_loading.cpp 175 - Loading shader file shaderpacks/default/shaders/gbuffers_damagedblock.vert.spv
03:37:36 [WARN ] shader_loading.cpp 181 - Could not read file shaderpacks/default/shaders/gbuffers_damagedblock.vert.spv
03:37:36 [ERROR] shader_loading.cpp 100 - std::exception
03:37:36 [TRACE] shader_loading.cpp 175 - Loading shader file shaderpacks/default/shaders/gbuffers_water.vsh
03:37:36 [WARN ] shader_loading.cpp 181 - Could not read file shaderpacks/default/shaders/gbuffers_water.vsh
03:37:36 [TRACE] shader_loading.cpp 175 - Loading shader file shaderpacks/default/shaders/gbuffers_water.vert
03:37:36 [WARN ] shader_loading.cpp 181 - Could not read file shaderpacks/default/shaders/gbuffers_water.vert
03:37:36 [TRACE] shader_loading.cpp 175 - Loading shader file shaderpacks/default/shaders/gbuffers_water.vert.spv
03:37:36 [WARN ] shader_loading.cpp 181 - Could not read file shaderpacks/default/shaders/gbuffers_water.vert.spv
03:37:36 [ERROR] shader_loading.cpp 100 - std::exception
03:37:36 [TRACE] shader_loading.cpp 175 - Loading shader file shaderpacks/default/shaders/gui.vsh
03:37:36 [WARN ] shader_loading.cpp 181 - Could not read file shaderpacks/default/shaders/gui.vsh
03:37:36 [TRACE] shader_loading.cpp 175 - Loading shader file shaderpacks/default/shaders/gui.vert
03:37:36 [TRACE] shader_loading.cpp 175 - Loading shader file shaderpacks/default/shaders/gui.fsh
03:37:36 [WARN ] shader_loading.cpp 181 - Could not read file shaderpacks/default/shaders/gui.fsh
03:37:36 [TRACE] shader_loading.cpp 175 - Loading shader file shaderpacks/default/shaders/gui.frag
03:37:36 [WARN ] shader_loading.cpp 121 - Could not find fallback shader gbuffers_textured for shader gui.
03:37:36 [TRACE] gl_shader_program.cpp 34 - Created shader program 3
03:37:36 [TRACE] nova_renderer.cpp 187 - 5 - Message from shader compiler of type other: FS SIMD8 shader: 27 inst, 0 loops, 408 cycles, 0:0 spills:fills, Promoted 0 constants, compacted 432 to 336 bytes.
03:37:36 [TRACE] nova_renderer.cpp 187 - 6 - Message from shader compiler of type other: FS SIMD16 shader: 27 inst, 0 loops, 460 cycles, 0:0 spills:fills, Promoted 0 constants, compacted 432 to 336 bytes.
03:37:36 [TRACE] nova_renderer.cpp 187 - 7 - Message from shader compiler of type other: VS vec4 shader: 18 inst, 0 loops, 104 cycles, 0:0 spills:fills, compacted 288 to 240 bytes.
03:37:36 [DEBUG] gl_shader_program.cpp 43 - Program gui linked successfully
03:37:36 [INFO ] nova_renderer.cpp 239 - Loading complete
03:37:36 [DEBUG] nova_renderer.cpp 242 - Linked up UBOs
[15:37:36] [Client thread/INFO]: Native code initialized
[15:37:37] [Client thread/INFO]: LWJGL Version: 2.9.4
[15:37:37] [Client thread/INFO]: Reloading ResourceManager: Default
[15:37:37] [Client thread/INFO]: Window was resized to: 854x480
[15:37:37] [Client thread/WARN]: Invalid sounds.json
java.lang.NullPointerException
        at java.io.Reader.<init>(Reader.java:78) ~[?:1.8.0_131]
        at java.io.InputStreamReader.<init>(InputStreamReader.java:72) ~[?:1.8.0_131]
        at net.minecraft.client.audio.SoundHandler.getSoundMap(SoundHandler.java:125) ~[main/:?]
        at net.minecraft.client.audio.SoundHandler.onResourceManagerReload(SoundHandler.java:74) [main/:?]
        at net.minecraft.client.resources.SimpleReloadableResourceManager.registerReloadListener(SimpleReloadableResourceManager.java:120) [main/:?]
        at net.minecraft.client.Minecraft.startGame(Minecraft.java:537) [main/:?]
        at net.minecraft.client.Minecraft.run(Minecraft.java:439) [main/:?]
        at net.minecraft.client.main.Main.main(Main.java:115) [main/:?]
        at Start.main(Start.java:9) [main/:?]
[15:37:37] [Sound Library Loader/INFO]: Starting up SoundSystem...
03:37:37 [FATAL] easylogging++.h 5627 - CRASH HANDLED; Application has crashed due to [SIGSEGV] signal
    ======= Backtrace: =========
    [1] /home/user/Desktop/nova/nova-renderer/jars/versions/1.10/1.10-natives/libnova-renderer.so+0x1c760a [0x7ff28a60460a]
    [2] /home/user/Desktop/nova/nova-renderer/jars/versions/1.10/1.10-natives/libnova-renderer.so+0x1c782b [0x7ff28a60482b]
    [3] /lib/x86_64-linux-gnu/libc.so.6+0x357f0 [0x7ff2b94cb7f0]
    [4] [0x7ff2a43f2fcc]

03:37:37 [WARN ] easylogging++.h 5627 - Aborting application. Reason: Fatal log at [/home/user/Desktop/nova/nova-renderer/src/main/cpp/3rdparty/easyloggingpp/src/easylogging++.h:5627]
./nova.sh: line 95: 20843 Aborted                 (core dumped) java -classpath ../build/classes/main:libraries:libraries/com/google/code/findbugs/jsr305/3.0.1/jsr305-3.0.1.jar:libraries/com/google/code/gson/gson/2.2.4/gson-2.2.4.jar:libraries/com/google/guava/guava/17.0/guava-17.0.jar:libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar:libraries/com/mojang/authlib/1.5.22/authlib-1.5.22.jar:libraries/com/mojang/netty/1.6/netty-1.6.jar:libraries/com/mojang/realms/1.9.1/realms-1.9.1.jar:libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar:libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar:libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar:libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar:libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar:libraries/commons-codec/commons-codec/1.9/commons-codec-1.9.jar:libraries/commons-io/commons-io/2.4/commons-io-2.4.jar:libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar:libraries/io/netty/netty-all/4.0.23.Final/netty-all-4.0.23.Final.jar:libraries/it/unimi/dsi/fastutil/7.0.12_mojang/fastutil-7.0.12_mojang.jar:libraries/net/java/dev/jna/jna/3.4.0/jna-3.4.0.jar:libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar:libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar:libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-windows.jar:libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar:libraries/net/sf/jopt-simple/jopt-simple/4.6/jopt-simple-4.6.jar:libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar:libraries/org/apache/commons/commons-lang3/3.3.2/commons-lang3-3.3.2.jar:libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar:libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar:libraries/org/apache/logging/log4j/log4j-api/2.0-beta9/log4j-api-2.0-beta9.jar:libraries/org/apache/logging/log4j/log4j-core/2.0-beta9/log4j-core-2.0-beta9.jar:libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar:libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-windows.jar:libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar:libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar:versions/1.10/1.10.jar -Djava.library.path=versions/1.10/1.10-natives Start
```
1. nova.sh setup, build, start.

**Comment by DethRaid** [comment]
What branch are you on?

**Comment by XakepSDK** [comment]
Just cloned repo by https. Master branch I think.

**Comment by DethRaid** [comment]
Are you on a Mac? There was something about LWJGL and my removal thereof breaking the sound system on Macs.

**Comment by XakepSDK** [comment]
Ubuntu 17.04

**Comment by DethRaid** [comment]
Alright. Imma have to look into it then

**Comment by Rayzr522** [comment]
Arch Linux 4.12.8, I just cloned the `chunks` branch and after fixing the numerous problems in `nova.sh`, I got Minecraft to start... only to end up with this issue. Any progress?

**Comment by DethRaid** [comment]
`nova.sh` and `nova.ps1` are deprecated. I don't think it'll give you different results, but try running `./gradlew runNova`

There has been no progress on this issue. I've been trying to get chunks working, which I've almost done, so I can start work on this soon

**Comment by Rayzr522** [comment]
If they're deprecated, what's the intended method of installation? The wiki still says to use `nova.ps1` for Windows.

**Comment by DethRaid** [comment]
./gradlew setup to setup nova and ./gradlew runNova to build and run nova I thought I updated the wiki past night but I'll check it when I get home

**Comment by DethRaid** [comment]
Closing this issue since you got past this step for issue #107
